#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

selection=$(curl -sL https://api.github.com/repos/leozide/leocad/releases/latest | jq -r '.assets[0].browser_download_url')

archive=${selection}

# get #

cd /tmp || exit

curl -sL                \
  --location            \
  --remote-header-name  \
  --remote-name         \
                        ${archive}

unzip					\
	-d /usr/bin			\
	-o					\
						./*.zip