#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# configuration #

console.directory "LeoCAD Software" "$PROOT_DIRECTORY"/home/"$user_name"/.config

# link configuration

console.inf "Linking configuration."
echo

[ -f /media/Internal/MEGA/Lego/leocad/leocad.conf ] &&									\
	ln -s -f																			\
		/media/Internal/MEGA/Lego/leocad/leocad.conf									\
		"$PROOT_DIRECTORY"/home/"$user_name"/.config/"LeoCAD Software"/LeoCAD.conf		|| :