#!/bin/bash

# dependencies #

# usage #

# variables #

scripts_list=(
	leocad-build
)

# run scripts

for script in ${scripts_list[@]}
do
	bash ${script}
done

# update binary

cp /usr/bin/leocad ./leocad

# upload changes

git add *

git commit -a -m "Build update"

git push
