#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

print_architecture="$(dpkg --print-architecture)"

home="/home/${SUDO_USER:-$USER}"

build_directory="/tmp/"
source="https://github.com/leozide/leocad.git"

# initial prompt clear #

clear

# packages #

install_list=(
	git
	hub
	g++
	make
	zlib1g-dev
	libqt5concurrent5
	libqt5opengl5
	libqt5opengl5-dev
	libqt5printsupport5
	libqt5xml5
	qt5-default
	qttools5-dev
	qttools5-dev-tools
)

# install #

console.inf "Installing required packages."
echo

console.install ${install_list[@]}

clear

# build #

console.fwd "Preparing build..."
echo

cd "$build_directory" || exit 1

git clone "$source"

cd "$build_directory"/leocad ||exit 1

# compile project

qmake leocad.pro

# compile binary

console.silence "make -s" &

console.spinner "Building..."
echo

clear

# update #

console.fwd "Updating binary..."
echo

# verify previous install/build existence

[ ! -z "$(which leocad)" ] && cp "$(which leocad)" "$(which leocad)".bak

# copy new binary

cp "$build_directory"/leocad/build/release/leocad /usr/bin/leocad

# clean #

# remove build directory

rm -rf "$build_directory"

# complete #

console.scs "Done."
echo