#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# get #

console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad /usr/bin

# url=https://github.com/leozide/leocad/releases/tag/continuous
# file=$(curl -sL "${url}" | grep LeoCAD-Linux-.*-arm64.zip | sed -e 's|<.*">||' | sed -e 's|<.*>||')

# curl -sL                  \
#    --location             \
#    --remote-header-name   \
#    --remote-name          \
#                           "${url}"/"${file}"
