#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

print_architecture="$(dpkg --print-architecture)"

home="/home/${SUDO_USER:-$USER}"

build_directory="/tmp/"
source="https://github.com/leozide/leocad.git"

# launcher #

# create architecture dependant launcher:
# add LD_PRELOAD to optimize performance on arm64 systems

console.inf "Writing launcher."
echo

cat <<- FILE > /usr/bin/leocad.desktop
[Desktop Entry]
Encoding=UTF-8
Name=LeoCAD
GenericName=LDraw Model Editor
Comment=LDraw Model Editor
Exec=/usr/bin/leocad
Icon=leocad
Terminal=false
Type=Application
MimeType=application/x-ldraw;application/x-multipart-ldraw;
Categories=Graphics;2DGraphics;3DGraphics;Editor;
FILE

if [[ "$print_architecture" = "arm64" ]]
then
	sed -i																						\
		-e 's|Exec.*|Exec=env LD_PRELOAD=/lib/libandroid-shmem-aarch64.so /usr/bin/leocad|g'	\
		/usr/bin/leocad.desktop
fi

chmod a+rx /usr/bin/leocad.desktop

# configuration #

console.directory "LeoCAD Software" "${home}"/.config

# link configuration

console.inf "Linking configuration."
echo

[ -d /media/Internal/MEGA/Lego/leocad/ ] &&					\
	ln -s -f												\
		/media/Internal/MEGA/Lego/leocad/leocad.conf		\
		"${home}"/.config/"LeoCAD Software"/LeoCAD.conf		|| :


