#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

application="leocad"

selection=$(curl -sL https://api.github.com/repos/leozide/leocad/releases/latest | jq -r '.assets[0].browser_download_url')

archive="${selection}"

# clean #

rm -rf /tmp/*.zip

# get #

cd /tmp || exit

console.dwl "Downloading ${application}..."
echo

curl						\
	--silent              	\
	--location            	\
	--remote-header-name  	\
	--remote-name         	\
                        	"${archive}"
# extract #

console.fwd "Extracting..."

console.silence "

unzip						\
	-qq						\
	-d /usr/bin				\
	-o						\
							./*.zip
"