#!/bin/bash

# dependencies #

source /data/data/com.termux/files/usr/bin/console
source /data/data/com.termux/files/usr/bin/globals

# usage #

# variables #

script=$(basename -- "${BASH_SOURCE[0]}")

# get #

console.get https://raw.githubusercontent.com/nathaneltitane/leocad/main leocad /usr/bin

# curl -sL                  \
#    --location             \
#    --remote-header-name   \
#    --remote-name          \
#        https://github.com/leozide/leocad/releases/download/continuous/LeoCAD-Linux-71ea45f-arm64.zip
